apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-conf
  labels:
    k8s-app: fluent-bit
data:
  fluent-bit.conf: |
    [SERVICE]
      flush   5
      daemon  off
      log_level info
      parsers_file parsers.conf

    [INPUT]
      name    tail
      tag     app.log
      path    /var/log/containers/surl*.log
      parser  json
      multiline.parser  docker

    [INPUT]
      name    dummy
      tag     dummy.log
      dummy   {"log":"2023-12-14T14:07:17.708Z  INFO 1 --- [nio-8080-exec-2] app.youngmon.surl.UrlController          : https://google.com\n","stream":"stdout","time":"2023-12-14T14:07:17.708511464Z"}

    [INPUT]
      name    tail
      tag     db.log
      path    /var/log/containers/mariadb*.log
      parser  docker
      multiline.parser  docker
    
    [FILTER]
      name   parser
      match  app.log
      key_name  log
      parser  spring_log
      
    [FILTER]
      name  parser
      match   dummy.log
      key_name  log
      parser  spring_log
    
    [OUTPUT]
      name  stdout
      match *
      format  json_lines

  parsers.conf: |
    [PARSER]
      Name        spring_log
      Format      regex        
      Regex       ^(?<date>\d{4}-\d{2}-\d{2})T(?<time>\d{2}:\d{2}:\d{2}.\d{3})Z\s+(?<level>\w+)\s+(?<pid>\d+)\s+---\s+\[(?<thread>[^\]]+)]\s+(?<logger>[^\s]+)\s+:\s+(?<message>.*)$
