apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-conf
  labels:
    k8s-app: fluent-bit
data:
  fluent-bit.conf: |
    [SERVICE]
      flush   5
      daemon  off
      log_level info
      parsers_file parsers.conf

    [INPUT]
      name    tail
      tag     app.log
      path    /var/log/containers/surl*.log
      parser  json
      multiline.parser  docker

    [INPUT]
      name    tail
      tag     db.log
      path    /var/log/containers/mariadb*.log
      parser  docker
      multiline.parser  docker
    
    [FILTER]
      name   parser
      match  app.log
      key_name  log
      parser  spring_log
      
    [FILTER]
      name  parser
      match   dummy.log
      key_name  log
      parser  spring_log
    
    [OUTPUT]
      name  stdout
      match *
      format  json_lines
      json_date_key false

      # 2023-12-14T13:22:58.778Z INFO 1 --- [nio-8080-exec-1] app.youngmon.surl.UrlController : https://google.com\n"
  parsers.conf: |
    [PARSER]
      Name        spring_log
      Format      regex        
      Regex       ^(?<time>\d{4}-\d{2}-\d{2}T\d{2}:\d{3}:\d{2}.\d{3}Z)\s+(?<level>\w+)\s+\d*\s+---\s+\[(?<thread>.*)\]\s+(?<logger>[^\s].*?[^\s])\s+:\s+(?<message>.*)
