apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: log-collector
spec:
  selector:
    matchLabels:
      name: fluentbit
  template:
    metadata:
      labels:
        name: fluentbit
    spec:
      containers:
      - name: fluentbit-container
        image: fluent/fluent-bit
        resources:
          limits:
            cpu: 50m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 10Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
          readOnly: true
        - name: varlogcontainers
          mountPath: /var/log/containers
          readOnly: true
        - name: mnt
          mountPath: /mnt
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc
        - name: varlogpods
          mountPath: /var/log/pods
      terminationGracePeriodSeconds: 10
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
          type: ""
      - name: varlogcontainers
        hostPath:
          path: /var/log/containers
          type: ""
      - name: varlogpods
        hostPath:
          path: /var/log/pods
          type: ""
      - name: mnt
        hostPath:
          path: /mnt
      - name: fluent-bit-config
        configMap:
          name: fluent-bit-conf
