# Dev
apiVersion: apps/v1
kind: Deployment
metadata:
  name: surl-deploy
  labels:
    app: surl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: surl
  template:
    metadata:
      labels:
        app: surl
    spec:
      containers:
      - name: surl-container
        image: surl
        imagePullPolicy: Never
        ports:
          - containerPort: 8080
        envFrom:
          - configMapRef:
              name: surl-conf
---
apiVersion: v1
kind: Service
metadata:
  name: surl
spec:
  type: NodePort
  selector:
    app: surl
  ports:
    - port: 8080
      targetPort: 8080
