apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prom-vol
  labels:
    for: minikube
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
