apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: server
  namespace: monitoring
  labels:
    app: prom-server
spec:
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  ruleNamespaceSelector: {}
  image: prom/prometheus
  replicas: 2
  serviceAccountName: prom-server
