apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      volumes:
      - name: vol
        persistentVolumeClaim:
          claimName: prometheus
      - name: prom-conf
        configMap:
          name: prometheus
      containers:
      - name: prometheus
        image: prom/prometheus
        ports:
          - containerPort: 9090
        volumeMounts:
          - name: vol
            mountPath: /var/lib/prometheus
          - name: prom-conf
            mountPath: /etc/prometheus/conf
