apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
  labels:
    for: minikube
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data
