apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: surl-monitor
  namespace: surl
spec:
  jobLabel: surl
  selector:
    matchLabels:
      metrics: surl
  endpoints:
    - port: metrics
      interval: 5s
      path: /actuator/prometheus
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: db-monitor
  namespace: surl
spec:
  jobLabel: database
  selector:
    matchLabels:
      metrics: db
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-state-metrics
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: kube-state-metrics
  endpoints:
    - port: http-metrics
