apiVersion: v1
kind: ServiceAccount
metadata:
  name: prom-adapter
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metric-role-binding
subjects:
  - kind: ServiceAccount
    name: prom-adapter
    namespace: monitoring
roleRef:
  kind: ClusterRole
  name: metrics-role
  apiGroup: rbac.authorization.k8s.io
