apiVersion: v1
kind: ServiceAccount
metadata:
  name: prom-server
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prom-server
  namespace: monitoring
subjects:
  - kind: ServiceAccount
    name: prom-server
    namespace: monitoring
roleRef:
  kind: ClusterRole
  name: scrape
  apiGroup: rbac.authorization.k8s.io
