apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: surl-hpa
  namespace: surl
  labels:
    app: surl-hpa
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: surl
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 30
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 40
