apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-exporter
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: node-exporter
  endpoints:
  - port: metrics
    interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: surl
  namespace: surl
spec:
  selector:
    matchLabels:
      app: surl
  endpoints:
    - port: main
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: database
  namespace: surl
spec:
  selector:
    matchLabels:
      app: database
  endpoints:
    - port: main
      interval: 15s
