apiVersion: v1
kind: Service
metadata:
  name: prom-server
  namespace: monitoring
  labels:
    app: prom-server
spec:
  type: NodePort
  selector:
    prometheus: server
  ports:
    - port: 9090
      targetPort: 9090
