apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: surl
  labels:
    app: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: db-container
        image: mariadb
        ports:
          - containerPort: 3306
        envFrom:
          - configMapRef:
              name: mariadb-env
