# Dev
apiVersion: apps/v1
kind: Deployment
metadata:
  name: surl
  namespace: surl
  labels:
    app: surl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: surl
  template:
    metadata:
      labels:
        app: surl
    spec:
      containers:
      - name: surl-container
        image: surl
        imagePullPolicy: Never
        ports:
          - containerPort: 8080
        envFrom:
          - configMapRef:
              name: backend-env
