apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
  namespace: monitoring
data:
  prometheus.yaml: |
    global:
      scrape_timeout: 10s
      scrape_interval: 15s
      evaluation_interval: 1m
    scrape_configs:
      - job_name: surl-scrape
        kubernetes_sd_configs:
          - role: pod
          selectors:
            - role: pod
              label: 'name=fluentbit'
