apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_timeout: 10s
      scrape_interval: 15s
      evaluation_interval: 1m
    scrape_configs:
      - job_name: surl-scrape
        kubernetes_sd_configs:
          - role: pod
            selectors:
            - role: pod
              label: 'name=fluentbit'
        relabel_configs:
          - source_labels: [__address__, __meta_kubernetes_pod_container_port_number]
            action: replace
            target_label: __address__
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
              #metrics_path: '/api/v2/metrics/prometheus'
