apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metrics-role
rules:
  - apiGroups: [""]
    resources:
      - pods
      - nodes
      - namespaces
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["authorization.k8s.io"]
    resources: ["subjectaccessreviews"]
    verbs: ["create"]
