apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit
  namespace: monitoring
  labels:
    app: fluentbit
data:
  fluent-bit.conf: |
    [SERVICE]
      daemon  off
      log_level info
      parsers_file custom_parser.conf
      http_server  On
      http_listen  0.0.0.0
      http_port    2021

    [INPUT]
      name    tail
      tag     log.surl
      path    /var/log/containers/surl*.log
      parser  docker

    [INPUT]
      name    tail
      tag     log.db
      path    /var/log/containers/mariadb*.log
      parser  docker
    
    [FILTER]
      name   parser
      match  log.surl
      key_name  log
      parser  spring_log
    
    [OUTPUT]
      name  stdout
      match *
      json_date_key false

  custom_parser.conf: |
    [PARSER]
      name        docker
      format      json
      tag         *

    [PARSER]
      name        spring_log
      format      regex
      tag         *
      regex       ^(?<date>\d{4}-\d{2}-\d{2})T(?<time>\d{2}:\d{2}:\d{2}.\d{3})Z\s+(?<level>\w+)\s+(?<pid>\d+)\s+---\s+\[(?<thread>[^\]]+)]\s+(?<logger>[^\s]+)\s+:\s+(?<message>.*)$
