apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: surl
  labels:
    app: database
spec:
  type: ClusterIP
  selector:
    app: mariadb
  ports:
    - name: main
      protocol: TCP
      port: 3306
      targetPort: 3306
