apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: surl
  labels:
    app: surl
spec:
  type: NodePort
  selector:
    app: surl
  ports:
    - name: web
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: metrics
  namespace: surl
  labels:
    metrics: surl
spec:
  selector:
    app: surl
  ports:
    - name: metrics
      port: 9100
      targetPort: 9100
