apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: surl
  labels:
    app: surl
spec:
  type: ClusterIP
  selector:
    app: surl
  ports:
    - name: web
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: metrics
  namespace: surl
  labels:
    metrics: surl
spec:
  selector:
    app: surl
  ports:
    - name: metrics
      protocol: TCP
      port: 9100
      targetPort: 9100
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend
  namespace: surl
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          service:
            name: backend
            port:
              number: 8080
        pathType: ImplementationSpecific
    host: ss.ymon.io
status:
  loadBalancer: {}
