name: Deploy to Cloud Run

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    
    - name: Build and Push Docker image
      run: | 
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/surl
    
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ${{ secrets.GCP_SERVICE_NAME }} \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/surl \
          --region ${{ secrets.GCP_REGION }} \
          --platform managed
