name: Deploy to Cloud Run

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    
    - name: Cache Gradle dependencies
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-${{ runner.os }}-
    
    - name: Build
      run: ./gradlew build

    - name: Auth With GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    
    - name: Set up Cloud CLI
      uses: google-github-actions/setup-gcloud@v1

    #  Cloud Build -> Docker
    - name: Build and Push Docker image
      run: | 
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_IMAGE_NAME }} .
        gcloud auth configure-docker
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_IMAGE_NAME }}
    
    ##     
    #- name: Deploy to Cloud Run
    #  run: |
    #    gcloud run deploy ${{ secrets.GCP_SERVICE_NAME }} \
    #      --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_IMAGE_NAME }} \
    #      --region ${{ secrets.GCP_REGION }} \
    #      --vpc-connector projects/${{ secrets.GCP_PROJECT_ID }}/locations/${{ secrets.GCP_REGION }}/connectors/${{ secrets.GCP_VPC_NAME }} \
    #      --platform managed
